[package]
name = "tun_tap"
version = "0.1.0"
authors = ["siegfried <zhiqiang.lei@gmail.com>"]
edition = "2018"
publish = ["tun_tap", "crates-io"]
homepage = "https://github.com/siegfried/tun_tap"
repository = "git@github.com:siegfried/tun_tap.git"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
travis-ci = { repository = "siegfried/tun_tap", branch = "master" }

[dependencies]
libc = "~0.2"
nix = "~0.17"

[dev-dependencies]
etherparse = "~0.9"
serial_test = "~0.4"